FROM node:22.1

WORKDIR /app

# Copiar archivos de dependencias para instalar primero
COPY package*.json ./

RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto donde corre Vite
EXPOSE 5173

# Comando para iniciar el servidor de desarrollo de Vite
CMD ["npm", "run", "dev"]
