version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ocean_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
