version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ocean_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgresql:12345@db:5432/ocean_db

  frontend:
    build: ./frontend
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
